In [29]:
import pandas as pd
import numpy as np

# Load Data Viz Pkgs
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.metrics import accuracy_score,hamming_loss,classification_report

### Split Dataset into Train and Text
from sklearn.model_selection import train_test_split
# Feature engineering
from sklearn.feature_extraction.text import TfidfVectorizer

from skmultilearn.adapt import MLkNN
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import string
import neattext as nt
import neattext.functions as nfx
from sklearn.utils import shuffle
import xgboost as xgb
from sklearn.multioutput import MultiOutputClassifier
from xgboost import XGBClassifier

In [30]:
df=pd.read_excel('test.xlsx')
#df = shuffle(df)
df

review  Bluetooth  \
0                                  Very X Very disappp          0   
1    I'm so glad that I finally got my hearing aids...          1   
2    It did not allow me to listen to the music in ...          0   
3    Just downloaded the app and I can’t get...          1   
4    Volume doesn't stays consistent when when usin...          0   
..                                                 ...        ...   
767  They produce a good hearing aid but a lousy ap...          0   
768  This app seems pretty unremarkable. While I am...          1   
769  This is a very poor product. There are several...          0   
770  Why? If I set the volume and treble/bass level...          0   
771  Your last upgrade has lost the compatibility t...          0   

     VC-Settings  Volume  
0              0       0  
1              0       0  
2              0       0  
3              0       0  
4              1       1  
..           ...     ...  
767            1       1  
768            1       0  
769            1       0  
770            1       0  
771            1       0  

[772 rows x 4 columns]

In [31]:
y = df[['Bluetooth', 'VC-Settings', 'Volume']]

In [32]:
corpus = df['review'].apply(nfx.remove_stopwords)

In [33]:
tfidf = TfidfVectorizer()

In [34]:
tfidf

TfidfVectorizer()

In [35]:
# Build Features
Xfeatures = tfidf.fit_transform(corpus).toarray()

In [36]:
Xfeatures

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [37]:
# Split Data 
X_train,X_test,y_train,y_test = train_test_split(Xfeatures,y,test_size=0.2,random_state=42)


In [38]:
from sklearn.ensemble import RandomForestClassifier

In [39]:
clf=RandomForestClassifier(n_estimators=100)

In [40]:
clf.fit(X_train,y_train)


RandomForestClassifier()

In [41]:
fr_prediction = clf.predict(X_test)

In [42]:
fr_prediction

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 1],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 1, 1],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 1],
       [1,

In [43]:
# Accuracy
accuracy_score(y_test,fr_prediction)

0.7870967741935484

In [44]:
import joblib

In [45]:
# Save Model
Random_Forest_clf_file = open("Random_Forest_clf_model_file.pkl","wb")
joblib.dump(clf,Random_Forest_clf_file)
Random_Forest_clf_file.close()


In [46]:
# Save Vectorizer
RF_tfidf_vectorizer_file = open("RF_tfidf_vectorizer.pkl","wb")
joblib.dump(tfidf,RF_tfidf_vectorizer_file)
RF_tfidf_vectorizer_file.close()

In [47]:
df2=pd.read_excel('Prediction data.xlsx')
df2

author                                             review  \
0      Raymond Miller  I just updated to this app. I can no longer he...   
1                5836  I spent 6000 on a pair of oticon opn s.  This ...   
2        Bert Okouchi  I really don't like the upgraded version, does...   
3       migueleishon0  though its alright, my only problem is that th...   
4           Mauri.A78  the music is not heard as expected, the bass i...   
...               ...                                                ...   
1450           wd0dir  This app really needs improvement. Very confus...   
1451    Bob Zambenini  Very poor andnot usable at times. Loses connec...   
1452  Johnny Keyboard  Does not connect to the best  new hearing aids...   
1453    Chris AlHadad  The app is frozen on the safety screen since i...   
1454            34544  I updated my iPhone today to iOS 14 and now fi...   

      stars     version       date       product    product_id  \
0         1       3.0.6 2020-06-17  280589732764  280589732764   
1         1       2.1.0 2020-06-17  216434795181  216434795181   
2         2  2.60.1.207 2020-06-17   40415998257   40415998257   
3         2  2.0.2.8660 2020-05-08  271100541311  271100541311   
4         1         1.3 2020-05-08   41767681958   41767681958   
...     ...         ...        ...           ...           ...   
1450      2       2.4.5 2020-09-17  280513936036  280513936036   
1451      1       3.1.0 2020-09-17  281133623603  281133623603   
1452      1      2.2.21 2020-09-17  281931183784  281931183784   
1453      1         4.0 2020-09-17  280709390796  280709390796   
1454      1         4.0 2020-09-17  280709390796  280709390796   

                product_name languages  
0                   myPhonak        en  
1                  Oticon ON        en  
2       Connexx Smart Remote        en  
3                  Oticon ON        en  
4                    COM-DEX        en  
...                      ...       ...  
1450    Connexx Smart Direct        en  
1451  Thrive Hearing Control        en  
1452              Rexton App        en  
1453                myPhonak        en  
1454                myPhonak        en  

[1455 rows x 9 columns]

In [48]:
model =joblib.load('Random_Forest_clf_model_file.pkl')
tfidf_model=joblib.load('RF_tfidf_vectorizer.pkl')

In [49]:
# Vectorized 
vec_example = tfidf_model.transform(df2['review'])

In [50]:
# Make our prediction
pre=model.predict(vec_example)

In [51]:
pre

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [52]:
df2["Bluetooth"]=pre[:,0]
df2["VC-Settings"]=pre[:,1]
df2["Volume"]=pre[:,2]

In [53]:
df2

author                                             review  \
0      Raymond Miller  I just updated to this app. I can no longer he...   
1                5836  I spent 6000 on a pair of oticon opn s.  This ...   
2        Bert Okouchi  I really don't like the upgraded version, does...   
3       migueleishon0  though its alright, my only problem is that th...   
4           Mauri.A78  the music is not heard as expected, the bass i...   
...               ...                                                ...   
1450           wd0dir  This app really needs improvement. Very confus...   
1451    Bob Zambenini  Very poor andnot usable at times. Loses connec...   
1452  Johnny Keyboard  Does not connect to the best  new hearing aids...   
1453    Chris AlHadad  The app is frozen on the safety screen since i...   
1454            34544  I updated my iPhone today to iOS 14 and now fi...   

      stars     version       date       product    product_id  \
0         1       3.0.6 2020-06-17  280589732764  280589732764   
1         1       2.1.0 2020-06-17  216434795181  216434795181   
2         2  2.60.1.207 2020-06-17   40415998257   40415998257   
3         2  2.0.2.8660 2020-05-08  271100541311  271100541311   
4         1         1.3 2020-05-08   41767681958   41767681958   
...     ...         ...        ...           ...           ...   
1450      2       2.4.5 2020-09-17  280513936036  280513936036   
1451      1       3.1.0 2020-09-17  281133623603  281133623603   
1452      1      2.2.21 2020-09-17  281931183784  281931183784   
1453      1         4.0 2020-09-17  280709390796  280709390796   
1454      1         4.0 2020-09-17  280709390796  280709390796   

                product_name languages  Bluetooth  VC-Settings  Volume  
0                   myPhonak        en          1            0       0  
1                  Oticon ON        en          0            0       0  
2       Connexx Smart Remote        en          0            0       0  
3                  Oticon ON        en          1            0       0  
4                    COM-DEX        en          0            0       0  
...                      ...       ...        ...          ...     ...  
1450    Connexx Smart Direct        en          0            0       0  
1451  Thrive Hearing Control        en          1            0       0  
1452              Rexton App        en          1            0       0  
1453                myPhonak        en          0            0       0  
1454                myPhonak        en          0            0       0  

[1455 rows x 12 columns]

In [54]:
df2.to_excel('Final_Auto_Prediction.xlsx')

In [55]:
################### APPLIED K-FOLD##############
from sklearn import model_selection
from sklearn.model_selection import KFold
kfold = model_selection.KFold(n_splits=10)
model_kfold =RandomForestClassifier(n_estimators=100)
results_kfold = model_selection.cross_val_score(model_kfold,Xfeatures,y, cv=kfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0))

Accuracy: 74.87%


In [56]:
#################### XG Boot######################
from sklearn.multiclass import OneVsRestClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import MultiLabelBinarizer
model = OneVsRestClassifier(XGBClassifier(n_jobs=-1, max_depth=4, eval_metric='mlogloss' , use_label_encoder =False))
model.fit(X_train,y_train)
acc = model.predict(X_test)
accuracy_score(y_test,acc)

0.7741935483870968